name: publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --no-restore
    - name: Test
      run: dotnet test ./src --no-build --verbosity normal
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: nuget.org
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: dotnet pack ./src -c Release -o "./nupkgs"
    - name: Publish
      run: dotnet nuget push "./*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      working-directory: nupkgs